[project]
name = "esc180-battery-sim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aaron Huang", email = "58890327+RunTheBot@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
esc180-battery-sim = "esc180_battery_sim:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
